language: python
python:
  - 2.7
  - 3.2
  - 3.3
script: python setup.py nosetests --with-coverage --cover-packages=image_slicer
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
after_success:
  - coveralls
notifications:
  email: false

